language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/test_reg_numbers

node_js:  
   - "12"

before_script:
  - psql -c 'create database  test_reg_numbers;' -U postgres
  - psql -U postgres -d test_reg_numbers -a -f table.sql

services:
  - postgresql